baseURL = "https://example.com/"
languageCode = "en-us"
title = "Create A Van Life"
theme = "blowfish"
enableRobotsTXT = true
enableEmoji = false
summaryLength = 40
paginate = 9
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[permalinks]
blog = "/blog/:contentbasename/"
gear = "/gear/:contentbasename/"
best-of = "/best-of/:contentbasename/"

[taxonomies]
tag = "tags"
category = "categories"

[sitemap]
changefreq = "weekly"
priority = 0.7
filename = "sitemap.xml"

[related]
threshold = 0
includeNewer = true
toLower = true
[[related.indices]]
name = "tags"
weight = 90
[[related.indices]]
name = "categories"
weight = 70
[[related.indices]]
name = "keywords"
weight = 40

[params]
plausibleDomain = "YOUR_DOMAIN_HERE"
