[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "Start Here"
pageRef = "/start-here"
weight = 1

[[main]]
name = "Best Picks"
pageRef = "/best-of"
weight = 40

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 50

[[main]]
name = "Deals"
pageRef = "/deals"
weight = 60

[[main]]
name = "About"
title = "About Create A Van Life"
pageRef = "/about"
weight = 70

[[main]]
name = "Disclosure"
pageRef = "/affiliate-disclosure"
weight = 80

[[footer]]
name = "Affiliate Disclosure"
pageRef = "/affiliate-disclosure"
weight = 10

[[footer]]
name = "Privacy"
pageRef = "/legal/privacy-policy"
weight = 20

[[footer]]
name = "Terms"
pageRef = "/legal/terms"
weight = 30

[[main]]
name = "Collections"
pageRef = "/collections"
weight = 45
